### ISSUE TITLE
Value {'software_version': '1.49.1949107040'} of type <class 'dict'> is invalid

### ISSUE THREAD

**Issue by SteffanH** [home-assistant-libs/aiohue#102]
After upgrade to HA Core 2021.12.8 I see the following warning in the logs
```
Logger: aiohue.util
Source: /usr/local/lib/python3.9/site-packages/aiohue/util.py:175
First occurred: 14:16:31 (1 occurrences)
Last logged: 14:16:31

Value {'software_version': '1.49.1949107040'} of type <class 'dict'> is invalid for Device.product_data, expected value of type typing.Optional[aiohue.v2.models.device.DeviceProductData]
```

and subsequently 
```Logger: aiohue.v2[192.168.1.245].events
Source: /usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/events.py:254
First occurred: 14:16:31 (2 occurrences)
Last logged: 14:26:25

Unable to parse Event message: data: [{"creationtime":"2022-01-05T13:16:25Z","data":[{"id":"729ef821-5391-4041-a34e-ebb04f8854f6","status":"pairing","type":"homekit"}],"id":"3d1dac3a-1466-4e1c-ba4c-0644d34a2929","type":"update"}]
Unable to parse Event message: data: [{"creationtime":"2022-01-05T13:26:25Z","data":[{"id":"729ef821-5391-4041-a34e-ebb04f8854f6","status":"unpaired","type":"homekit"}],"id":"318674fb-8536-4bc1-b230-dc6da7d693cf","type":"update"}]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/events.py", line 244, in __parse_message
    clip_event = CLIPEvent.from_dict(event)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/models/clip.py", line 117, in from_dict
    data=[parse_clip_resource(x) for x in dict_in["data"]],
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/models/clip.py", line 117, in <listcomp>
    data=[parse_clip_resource(x) for x in dict_in["data"]],
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/models/clip.py", line 94, in parse_clip_resource
    return dataclass_from_dict(resource_cls, obj_in, strict=False)
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 193, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 194, in <dictcomp>
    field.name: _get_val(
  File "/usr/local/lib/python3.9/site-packages/aiohue/util.py", line 149, in _get_val
    return [
TypeError: 'NoneType' object is not iterable
```
Not sure if they're related or not: if not, I'm more than happy to create a separate issue.
Also have no idea what additional information (if any) might be useful ?

**Comment by SteffanH** [comment]
ok

**Comment by marcelveldt** [comment]
Reopened as reminder to myself to look at this one day to maybe workaround it

**Comment by balloob** [comment]
Yeah would be nice if we can at least not print the warning.
