### ISSUE TITLE
KeyError: 'bridgeid'

### ISSUE THREAD

**Issue by mamoel666** [home-assistant-libs/aiohue#134]
I run HA 2022.4.7 in a Docker container (Intel NUC11, Ubuntu 20.04.4 LTS).

I am not sure when this started, but after every restart I see this in the logs:

```
2022-04-27 17:10:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 192, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 190, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
result = await self._async_handle_step(flow, flow.init_step, data, init_done)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/usr/src/homeassistant/homeassistant/components/hue/config_flow.py", line 241, in async_step_ssdp
self.bridge = await self._get_bridge(
File "/usr/src/homeassistant/homeassistant/components/hue/config_flow.py", line 75, in _get_bridge
bridge = await discover_bridge(
File "/usr/local/lib/python3.9/site-packages/aiohue/discovery.py", line 35, in discover_bridge
bridge_id = await is_hue_bridge(host, websession)
File "/usr/local/lib/python3.9/site-packages/aiohue/discovery.py", line 82, in is_hue_bridge
return normalize_bridge_id(data["bridgeid"])
KeyError: 'bridgeid'
```
I've seen [this post](https://community.home-assistant.io/t/help-log-details-error-logger-homeassistant-source-components-hue-config-flow-py-75/413954) in the official community - so I am not the only one with this message.

**Comment by mamoel666** [comment]
Then maybe it‘s the Node-Red extension „ node-red-contrib-amazon-echo-oztourer“. It emulates a Hue bridge in Node-Red.

**Comment by marcelveldt** [comment]
Yep, that is the answer. It emulates a Hue bridge but it doesn't do that 100% exactly like a Hue bridge.
Our discovery in HA discovers the emulated bridge and tries to query it, resulting in this error.

Best way would be if those emulator projects just fix their response but we'll try to workaround it in our discovery code.

**Comment by danielbrunt57** [comment]
Same error here and it was [node-red-contrib-amazon-echo 0.1.10](https://flows.nodered.org/node/node-red-contrib-amazon-echo).  Removed my experimental flows and that node from Node-RED, restarted HA and...
![image](https://user-images.githubusercontent.com/49846893/176962083-08faa960-161c-4b52-9714-d3972fafb8c4.png)
