### ISSUE TITLE
Unable to parse resource, please report this to the authors of aiohue.

### ISSUE THREAD

**Issue by ShadowRep** [home-assistant-libs/aiohue#140]
Everything seems to work fine but the log says I should report it, so here you go:

```
Logger: aiohue.v2[192.168.2.25].entertainment_configuration
Source: /usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py:210
First occurred: 00:41:11 (1 occurrences)
Last logged: 00:41:11

Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 209, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 210, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 180, in _parse_value
    return value_type(value)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'monitor' is not a valid EntertainmentConfigurationType
```

A restart does not help, the issue persists.

**Comment by ShadowRep** [comment]
Thanks!
