### ISSUE TITLE
aiohue.v2[10.1.1.232].scene] Unable to parse resource, 

### ISSUE THREAD

**Issue by instinxx** [home-assistant-libs/aiohue#185]
Getting a ton of these errors in the logs. Not sure why or if I can resolve it. Any thoughts?

2023-02-21 19:31:40.856 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 212, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 213, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 181, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.auto_dynamic` of type `<class 'bool'>` is required."
2023-02-21 19:31:40.859 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 212, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 213, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 181, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.auto_dynamic` of type `<class 'bool'>` is required."
2023-02-21 19:31:40.859 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 212, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 213, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 181, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.auto_dynamic` of type `<class 'bool'>` is required."
2023-02-21 19:31:40.860 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 212, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 213, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 181, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.auto_dynamic` of type `<class 'bool'>` is required."
2023-02-21 19:31:40.863 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 212, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 213, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 181, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.auto_dynamic` of type `<class 'bool'>` is required."
2023-02-21 19:31:40.863 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 212, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 213, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 181, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.auto_dynamic` of type `<class 'bool'>` is required."
2023-02-21 19:31:40.864 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 212, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 213, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 181, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.auto_dynamic` of type `<class 'bool'>` is required."
2023-02-21 19:31:40.865 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 212, in dataclass_from_dict
    **{
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 213, in <dictcomp>
    field.name: _parse_value(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 181, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.auto_dynamic` of type `<class 'bool'>` is required."
2023-02-21 19:31:40.865 ERROR (MainThread) [aiohue.v2[10.1.1.232].scene] Unable to parse resource, please report this to the authors of aiohue.

**Comment by marcelveldt** [comment]
Can you check if your bridge is behind on firmware updates ?
