### ISSUE TITLE
aiohue.v2[192.168.0.107].scene] Unable to parse resource

### ISSUE THREAD

**Issue by gatisr** [home-assistant-libs/aiohue#259]
Hue Bridge Version: 1.60.1960149090

Connected Device: Hue Play Gradient Lightstrip

Issue:
Encountered the following error while running Home Assistant today:
```
2023-11-17 07:04:59.506 ERROR (MainThread) [aiohue.v2[192.168.0.107].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohue/v2/controllers/base.py", line 194, in _handle_event
cur_item = self._items[item_id] = dataclass_from_dict(self.item_cls, evt_data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 239, in dataclass_from_dict
**{
^
File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 240, in <dictcomp>
field.name: _parse_value(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 198, in _parse_value
raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.palette` of type `<class 'aiohue.v2.models.feature.PaletteFeature'>` is required."
```

Additional Information:

Home Assistant Version: 2023.11.2

Please assist in resolving this issue. Thank you!

**Comment by jamesremuscat** [comment]
Same here - it looks like aiohue is treating `palette` as required, when the [Hue API](https://developers.meethue.com/develop/hue-api-v2/api-reference/#resource_scene_get) does not; and indeed, none of the scenes in my system have a `palette` entry.

(I'm using diyhue, but OP is using a genuine hub, so that doesn't seem to be the issue at play here.)
