### ISSUE TITLE
Errors in homeassistant.log

### ISSUE THREAD

**Issue by albaintor** [home-assistant-libs/aiohue#295]
Hi,

I have multiple errors in Homeassistant.log
The integration works fine though
Thank you

`2024-02-04 14:23:47.209 ERROR (MainThread) [aiohue.v2[192.168.1.107].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohue/v2/controllers/base.py", line 194, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(self.item_cls, evt_data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 239, in dataclass_from_dict
    **{
      ^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 240, in <dictcomp>
    field.name: _parse_value(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 198, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.palette` of type `<class 'aiohue.v2.models.feature.PaletteFeature'>` is required."
2024-02-04 14:23:47.234 ERROR (MainThread) [aiohue.v2[192.168.1.107].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohue/v2/controllers/base.py", line 194, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(self.item_cls, evt_data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 239, in dataclass_from_dict
    **{
      ^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 240, in <dictcomp>
    field.name: _parse_value(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 198, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.palette` of type `<class 'aiohue.v2.models.feature.PaletteFeature'>` is required."
2024-02-04 14:23:47.244 ERROR (MainThread) [aiohue.v2[192.168.1.107].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohue/v2/controllers/base.py", line 194, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(self.item_cls, evt_data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 239, in dataclass_from_dict
    **{
      ^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 240, in <dictcomp>
    field.name: _parse_value(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 198, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`Scene.palette` of type `<class 'aiohue.v2.models.feature.PaletteFeature'>` is required."
2024-02-04 14:23:47.253 ERROR (MainThread) [aiohue.v2[192.168.1.107].scene] Unable to parse resource, please report this to the authors of aiohue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohue/v2/controllers/base.py", line 194, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(self.item_cls, evt_data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 239, in dataclass_from_dict
    **{
      ^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 240, in <dictcomp>
    field.name: _parse_value(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 198, in _parse_value`

**Comment by marcelveldt** [comment]
this has been fixed by #262
