### ISSUE TITLE
aiohue/sensors.py, line 195: IndexError: list index out of range 

### ISSUE THREAD

**Issue by Jo-Bl** [home-assistant-libs/aiohue#327]
[user@ArchL bin]$ ./hue2mqtt
hue2mqtt INFO Hue2MQTT v0.4.1 - Hue to MQTT Bridge.
hue2mqtt INFO Connected to MQTT Broker
hue2mqtt INFO Connecting to Hue Bridge at 192.168.10.10
hue2mqtt INFO Bridge Name: PhilipsHueJ
hue2mqtt INFO Bridge MAC: 00:17:88:44:11:22
hue2mqtt INFO API Version: 1.60.0
Traceback (most recent call last):
  File "/home/user/hue2mqtt/bin/./hue2mqtt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/hue2mqtt/app.py", line 24, in app
    loop.run_until_complete(hue2mqtt.run())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/hue2mqtt/hue2mqtt.py", line 109, in run
    await self.main(websession)
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/hue2mqtt/hue2mqtt.py", line 220, in main
    async for updated_object in self._bridge.listen_events():
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/aiohue/bridge.py", line 232, in listen_events
    obj = getattr(self, item_type).process_event(event["type"], event_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/aiohue/api.py", line 70, in process_event
    meth(data)
  File "/home/user/hue2mqtt/lib/python3.11/site-packages/aiohue/sensors.py", line 195, in process_update_event
    for event in self.inputs[idx]["events"]:
                 ~~~~~~~~~~~^^^^^
IndexError: list index out of range

**Comment by marcelveldt** [comment]
Please specify a little bit more context please. What devices, what version of aiohue ?
