### ISSUE TITLE
Connection reset by peer v1 api

### ISSUE THREAD

**Issue by thcipriani** [home-assistant-libs/aiohue#344]
Seeing this in my home assistant logs:

```
Logger: homeassistant.core
Source: core.py:2559
First occurred: April 14, 2024 at 10:06:20 AM (16855 occurrences)
Last logged: 1:01:18 PM

Error executing service: <ServiceCall light.turn_on (c:<redacted>): entity_id=['light.kitchen_1'], params=transition=1.0, brightness=254, color_temp=181, color_temp_kelvin=5524>
Error executing service: <ServiceCall light.turn_on (c:<redacted>): entity_id=['light.kitchen_3'], params=transition=1.0, brightness=254, color_temp=181, color_temp_kelvin=5524>
Error executing service: <ServiceCall light.turn_on (c:<redacted>): entity_id=['light.kitchen_4'], params=transition=1.0, brightness=254, color_temp=181, color_temp_kelvin=5524>
Error executing service: <ServiceCall light.turn_on (c:<redacted>): entity_id=['light.kitchen_5'], params=transition=1.0, brightness=254, color_temp=181, color_temp_kelvin=5524>
Error executing service: <ServiceCall light.turn_on (c:<redacted>): entity_id=['light.kitchen_2'], params=transition=1.0, brightness=254, color_temp=181, color_temp_kelvin=5524>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1065, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 128, in async_request_call
    return await task(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohue/v1/lights.py", line 142, in set_state
    await self._request("put", f"lights/{self.id}/state", json=data)
  File "/usr/local/lib/python3.12/site-packages/aiohue/v1/__init__.py", line 137, in request
    async with self._websession.request(method, url, json=json) as resp:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2559, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 971, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1043, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 631, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/hue/v1/light.py", line 581, in async_turn_on
    await self.bridge.async_request_call(self.light.set_state, **command)
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 139, in async_request_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Request failed due connection error: [Errno 104] Connection reset by peer
```

It's always for these kitchen lights for some reason. The bulbs are:

```
{
  "state": {
    "on": true,
    "bri": 253,
    "ct": 181,
    "alert": "none",
    "colormode": "ct",
    "reachable": true
  },
  "type": "Color temperature light",
  "name": "Kitchen 5",
  "modelid": "LTG001",
  "manufacturername": "Philips",
  "uniqueid": "<redacted>",
  "swversion": "1.65.11_hB798F2",
  "swconfigid": "FCD5208A",
  "productid": "Philips-LTG001-3-GU10CTv2"
}
```

This may be the same issue from https://github.com/home-assistant/core/issues/13389 but it's been a few years and it's morphed a bit.

Seems like the webrequest code is robust for retrying in the case of http errors, but not tcp issues. Maybe adding a try block here: https://github.com/home-assistant-libs/aiohue/blob/main/aiohue/v1/__init__.py#L138 and using the same retry logic?

I'm happy to try that and submit a PR if that seems like the right path. The only caveat I have is that I'm running the homeassistant vm and I really have no idea where this code lives, honestly.

**Comment by marcelveldt** [comment]
The V1 code is unmaintained, sorry. I suggest you switch to a V2 bridge or try to PR the fix yourself.
Thanks
